# -*- coding: utf-8 -*-
"""pramodjadhav_stage2.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfMpYRJT2XSj00xrUPV_ukl4jtbVfNW2
"""

def calculator():
    try:
        num1 = float(input("Enter first number: "))
    except ValueError:
        print("Invalid input for the first number. Please enter a valid number.")
        return

    operator = input("Enter operator (+, -, *, /): ")

    try:
        num2 = float(input("Enter second number: "))
    except ValueError:
        print("Invalid input for the second number. Please enter a valid number.")
        return

    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        if num2 != 0:
            result = num1 / num2
        else:
            print("Error: Division by zero!")
            return
    else:
        print("Invalid operator!")
        return

    print(f"Result = {result}")

    # Stage 2: Add Result Check
    if result > 0:
        print("Positive")
    elif result < 0:
        print("Negative")
    else:
        print("Zero")

calculator()