# -*- coding: utf-8 -*-
"""pramodjadhav_stage1-ipy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/pramodj551-oss/e872f7bccc4d71502fca606c8dd5eede/pramodjadhav_stage1-ipy.ipynb
"""

# Stage 1: Basic Calculator
def calculator():
    num1 = float(input("Enter first number: "))
    operator = input("Enter operator (+, -, *, /): ")
    num2 = float(input("Enter second number: "))

    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        if num2 != 0:
            result = num1 / num2
        else:
            print("Error: Division by zero!")
            return
    else:
        print("Invalid operator!")
        return

    print(f"Result = {result}")

calculator()